// <auto-generated />
using System;
using HeriStep.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeriStep.API.Migrations
{
    [DbContext(typeof(HeriStepDbContext))]
    [Migration("20260312080603_FixSortOrderMapping")]
    partial class FixSortOrderMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeriStep.Shared.Models.Language", b =>
                {
                    b.Property<string>("LangCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("lang_code");

                    b.Property<string>("FlagIconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LangName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lang_name");

                    b.HasKey("LangCode");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_thumb")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit")
                        .HasColumnName("is_open")
                        .HasJsonPropertyName("isOpen");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude")
                        .HasJsonPropertyName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude")
                        .HasJsonPropertyName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_default")
                        .HasJsonPropertyName("name");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id")
                        .HasJsonPropertyName("ownerId");

                    b.Property<int>("RadiusMeter")
                        .HasColumnType("int")
                        .HasColumnName("radius_meter")
                        .HasJsonPropertyName("radiusMeter");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order")
                        .HasJsonPropertyName("sortOrder");

                    b.Property<int?>("TourID")
                        .HasColumnType("int")
                        .HasColumnName("TourID")
                        .HasJsonPropertyName("tourId");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Stalls", null, t =>
                        {
                            t.HasTrigger("SomeTriggerName");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsSignature")
                        .HasColumnType("bit")
                        .HasColumnName("is_signature");

                    b.Property<int>("StallId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.StallVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_id");

                    b.Property<int>("StallId")
                        .HasColumnType("int")
                        .HasColumnName("stall_id");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("visited_at");

                    b.HasKey("Id");

                    b.ToTable("StallVisits", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activation_code");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTopHot")
                        .HasColumnType("bit")
                        .HasColumnName("is_top_hot");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tour_name");

                    b.HasKey("Id");

                    b.ToTable("Tours", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.StallContent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lang_code");

                    b.Property<int>("StallId")
                        .HasColumnType("int")
                        .HasColumnName("stall_id");

                    b.Property<string>("TtsScript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tts_script");

                    b.HasKey("id");

                    b.ToTable("StallContents", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
