// <auto-generated />
using System;
using HeriStep.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeriStep.API.Migrations
{
    [DbContext(typeof(HeriStepDbContext))]
    [Migration("20260407064103_UpdateDatabaseSchema")]
    partial class UpdateDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeriStep.Shared.Models.Language", b =>
                {
                    b.Property<string>("LangCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("lang_code");

                    b.Property<string>("FlagIconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LangName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lang_name");

                    b.HasKey("LangCode");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsSignature")
                        .HasColumnType("bit")
                        .HasColumnName("is_signature");

                    b.Property<int>("StallId")
                        .HasColumnType("int")
                        .HasColumnName("stall_id");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.ProductTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LangCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lang_code");

                    b.Property<string>("ProductDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_desc");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_name");

                    b.HasKey("Id");

                    b.ToTable("ProductTranslations", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Stall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_thumb");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit")
                        .HasColumnName("is_open");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_default");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int>("RadiusMeter")
                        .HasColumnType("int")
                        .HasColumnName("radius_meter");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<int?>("TourID")
                        .HasColumnType("int")
                        .HasColumnName("TourID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TourID");

                    b.ToTable("Stalls", null, t =>
                        {
                            t.HasTrigger("SomeTriggerName");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.StallVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_id");

                    b.Property<int>("StallId")
                        .HasColumnType("int")
                        .HasColumnName("stall_id");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("visited_at");

                    b.HasKey("Id");

                    b.ToTable("StallVisits", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activation_code");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("StallId")
                        .HasColumnType("int")
                        .HasColumnName("stall_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("StallId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.TicketPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationHours")
                        .HasColumnType("int")
                        .HasColumnName("duration_hours");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PackageName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("package_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("TicketPackages", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTopHot")
                        .HasColumnType("bit")
                        .HasColumnName("is_top_hot");

                    b.Property<string>("TourName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tour_name");

                    b.HasKey("Id");

                    b.ToTable("Tours", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.TouristTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<string>("TicketCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ticket_code");

                    b.HasKey("Id");

                    b.ToTable("TouristTickets", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "System Admin",
                            PasswordHash = "$2a$11$n/A1qU55YyC7o2s1K0kC1O/0wA1oHh5X2w3E1z8e7H7A9R2lX4m",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HeriStep.Shared.StallContent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LangCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lang_code");

                    b.Property<int>("StallId")
                        .HasColumnType("int")
                        .HasColumnName("stall_id");

                    b.Property<string>("TtsScript")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tts_script");

                    b.HasKey("id");

                    b.ToTable("StallContents", (string)null);
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Stall", b =>
                {
                    b.HasOne("HeriStep.Shared.Models.Tour", null)
                        .WithMany("Stalls")
                        .HasForeignKey("TourID");
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Subscription", b =>
                {
                    b.HasOne("HeriStep.Shared.Models.Stall", "Stall")
                        .WithMany("Subscriptions")
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Stall", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("HeriStep.Shared.Models.Tour", b =>
                {
                    b.Navigation("Stalls");
                });
#pragma warning restore 612, 618
        }
    }
}
