using HeriStep.Shared.Models.DTOs.Requests;
using HeriStep.Shared.Models.DTOs.Responses;
using BCrypt.Net;
using HeriStep.API.Data;
using HeriStep.Shared.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace HeriStep.API.Controllers { [Route("api/[controller]")][ApiController] public class AuthController : ControllerBase { private readonly HeriStepDbContext _context; public AuthController(HeriStepDbContext context) { _context = context; }          /*  ========================================== */ /*  1. CH?C NANG ÐANG KÝ (Dành cho Admin c?p tài kho?n) */ /*  ========================================== */ [HttpPost("register")] public async Task<IActionResult> Register([FromBody] RegisterRequest req) { if (await _context.Users.AnyAsync(u => u.Username == req.Username)) return BadRequest("S? di?n tho?i này dã du?c c?p tài kho?n r?i!");              /*  ?? Bam m?t kh?u b?ng BCrypt */ string hashedPassword = BCrypt.Net.BCrypt.HashPassword(req.Password); var newUser = new User { Username = req.Username, PasswordHash = hashedPassword, FullName = req.FullName, Role = req.Role ?? "StallOwner" }; _context.Users.Add(newUser); await _context.SaveChangesAsync(); return Ok(new { message = "T?o tài kho?n thành công!", username = newUser.Username }); }          /*  ========================================== */ /*  2. CH?C NANG ÐANG NH?P */ /*  ========================================== */ [HttpPost("login")] public async Task<IActionResult> Login([FromBody] LoginRequest req) { var user = await _context.Users.FirstOrDefaultAsync(u => u.Username == req.Username); if (user == null) { return Unauthorized(new { message = "Sai tài kho?n ho?c m?t kh?u!" }); } bool isPasswordValid = false;              /*  Ki?m tra tru?ng h?p d?c bi?t: M?t kh?u chua mã hóa (n?u s?p l? tay nh?p tr?c ti?p vào SQL) */ if (user.PasswordHash == req.Password) { isPasswordValid = true; } else {                 /*  ?? Gi?i mã và so sánh b?ng BCrypt */ try { isPasswordValid = BCrypt.Net.BCrypt.Verify(req.Password, user.PasswordHash); } catch { } /*  Tránh s?p server n?u chu?i hash trong DB b? l?i d?nh d?ng */ } if (!isPasswordValid) { return Unauthorized(new { message = "Sai tài kho?n ho?c m?t kh?u!" }); } return Ok(new { userId = user.Id, role = user.Role, fullName = user.FullName, username = user.Username }); } }      /*  --- DTOs (Data Transfer Objects) --- */ public class LoginRequest { public string Username { get; set; } = ""; public string Password { get; set; } = ""; } public class RegisterRequest { public string Username { get; set; } = ""; public string Password { get; set; } = ""; public string FullName { get; set; } = ""; public string? Role { get; set; } } }

