using HeriStep.Shared.Models.DTOs.Requests;
using HeriStep.Shared.Models.DTOs.Responses;
using HeriStep.API.Data;
using HeriStep.Shared;
using HeriStep.Shared.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace HeriStep.API.Controllers { [Route("api/[controller]")][ApiController] public class PointsController : ControllerBase { private readonly HeriStepDbContext _context; public PointsController(HeriStepDbContext context) { _context = context; }          /*  1. L?Y DANH SÁCH (JOIN 3 B?NG: Stalls, StallContents, Users) */ [HttpGet] public async Task<ActionResult<IEnumerable<Stall>>> GetPoints() { var points = await (from s in _context.Stalls                                     /*  Join l?y n?i dung ti?ng Vi?t */ join c in _context.StallContents on s.Id equals c.StallId where c.LangCode == "vi"                                  /*  ?? THÊM ÐO?N NÀY: LEFT JOIN v?i b?ng Users d? l?y tên Ch? s?p */ join u in _context.Users on s.OwnerId equals u.Id into userGroup from user in userGroup.DefaultIfEmpty() select new Stall { Id = s.Id, OwnerId = s.OwnerId,                               /*  L?y mã Ch? s?p */ OwnerName = user != null ? user.FullName : null,   /*  L?y tên Ch? s?p */ Name = s.Name, Latitude = s.Latitude, Longitude = s.Longitude, RadiusMeter = s.RadiusMeter, ImageUrl = s.ImageUrl, IsOpen = s.IsOpen, UpdatedAt = s.UpdatedAt, TourID = s.TourID, TtsScript = c.TtsScript }).ToListAsync(); return points; }          /*  2. THÊM M?I (LUU VÀO HAI B?NG) */ [HttpPost] public async Task<ActionResult<Stall>> PostPoint(Stall point) {             /*  BU?C A: Luu thông tin k? thu?t vào b?ng Stalls */ _context.Stalls.Add(point); await _context.SaveChangesAsync();              /*  BU?C B: Luu n?i dung thuy?t minh vào b?ng StallContents */ var content = new StallContent { StallId = point.Id, LangCode = "vi", TtsScript = point.TtsScript ?? "", IsActive = true }; _context.StallContents.Add(content); await _context.SaveChangesAsync(); return CreatedAtAction(nameof(GetPoints), new { id = point.Id }, point); }         /*  THÊM VÀO PointsController.cs */ /*  API: L?y danh sách s?p theo Mã Ch? S?p */ [HttpGet("owner/{ownerId}")] public async Task<ActionResult<IEnumerable<Stall>>> GetStallsByOwner(int ownerId) { var stalls = await _context.Stalls.Where(s => (int?)s.OwnerId == ownerId).ToListAsync(); if (!stalls.Any()) { return NotFound(new { message = "B?n chua có s?p hàng nào qu?n lí , hãy liên h? admin d? du?c h? tr?" }); } return Ok(stalls); } } }

